# Streamlit secrets — local dev (.streamlit/secrets.toml)
# Di Streamlit Cloud, masukkan key ini di Settings → Secrets
OPENROUTER_API_KEY = "sk-or-v1-xxxxxxxxxxxxxxxx"  # ganti dgn kunci OpenRouter kamu
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbyMq2vZmQpJDIzYZtm9th83JuhsCWAuixt3qnvX31yIUqK71eNEXFJHj08SHDdONyCp/exec"
APPS_SCRIPT_TOKEN = "pp-305...b9c0"
